-- Only insert default settings (table and policies already exist)
INSERT INTO site_settings (setting_key, setting_value, setting_type, category, description) VALUES
  ('site_name', 'Crafted Anomaly', 'text', 'general', 'Website name displayed in browser title'),
  ('site_description', 'Museum-Grade Portfolio - Design Studio', 'text', 'general', 'Website description for SEO'),
  ('company_name', 'Crafted Anomaly', 'text', 'general', 'Company name'),
  ('company_tagline', 'Crafting Dreams Into Reality', 'text', 'general', 'Company tagline'),
  ('contact_email', 'hello@craftedanomaly.com', 'email', 'contact', 'Primary contact email'),
  ('contact_phone', '+90 xxx xxx xx xx', 'text', 'contact', 'Contact phone number'),
  ('contact_address', 'Istanbul, Turkey', 'text', 'contact', 'Company address'),
  ('logo_url', '/Anomaly.png', 'url', 'branding', 'Main logo URL'),
  ('logo_alt', 'Crafted Anomaly', 'text', 'branding', 'Logo alt text'),
  ('favicon_url', '/Anomaly.png', 'url', 'branding', 'Favicon URL'),
  ('social_instagram', '', 'url', 'social', 'Instagram profile URL'),
  ('social_twitter', '', 'url', 'social', 'Twitter profile URL'),
  ('social_linkedin', '', 'url', 'social', 'LinkedIn profile URL'),
  ('social_behance', '', 'url', 'social', 'Behance profile URL'),
  ('social_dribbble', '', 'url', 'social', 'Dribbble profile URL'),
  ('social_youtube', '', 'url', 'social', 'YouTube channel URL'),
  ('about_title_en', 'about', 'text', 'content', 'About section title (English)'),
  ('about_title_tr', 'hakkımızda', 'text', 'content', 'About section title (Turkish)'),
  ('about_text_en', 'crafted anomaly is a design studio that transforms visions into tangible experiences. we specialize in creating museum-grade portfolios that blur the lines between art and functionality.', 'textarea', 'content', 'About section text (English)'),
  ('about_text_tr', 'crafted anomaly, vizyonları somut deneyimlere dönüştüren bir tasarım stüdyosudur. sanat ve işlevsellik arasındaki çizgileri bulanıklaştıran müze kalitesinde portföyler oluşturma konusunda uzmanız.', 'textarea', 'content', 'About section text (Turkish)'),
  ('about_image_url', '', 'url', 'content', 'About section studio image URL'),
  ('footer_explore_title', 'explore', 'text', 'footer', 'Footer explore section title'),
  ('footer_contact_title', 'contact', 'text', 'footer', 'Footer contact section title'),
  ('footer_bottom_text', 'crafted with care in istanbul', 'text', 'footer', 'Footer bottom right text'),
  ('footer_copyright_text', 'all rights reserved', 'text', 'footer', 'Footer copyright text'),
  ('contact_page_title', 'get in touch', 'text', 'contact_page', 'Contact page main title'),
  ('contact_page_subtitle', 'let''s discuss your next project and bring your vision to life', 'text', 'contact_page', 'Contact page subtitle'),
  ('contact_info_title', 'contact information', 'text', 'contact_page', 'Contact information section title'),
  ('contact_info_description', 'Feel free to reach out through any of these channels. We typically respond within 24 hours.', 'textarea', 'contact_page', 'Contact information description'),
  ('working_hours_title', 'working hours', 'text', 'contact_page', 'Working hours section title'),
  ('working_hours_monday_friday', 'Monday - Friday: 9:00 AM - 6:00 PM', 'text', 'contact_page', 'Monday to Friday working hours'),
  ('working_hours_saturday', 'Saturday: 10:00 AM - 4:00 PM', 'text', 'contact_page', 'Saturday working hours'),
  ('working_hours_sunday', 'Sunday: Closed', 'text', 'contact_page', 'Sunday working hours'),
  ('contact_consent_text', 'I consent to being contacted via email regarding this inquiry', 'text', 'contact_page', 'Contact form consent text'),
  ('homepage_fields_title_en', 'our fields', 'text', 'homepage', 'Homepage fields section title (English)'),
  ('homepage_fields_title_tr', 'alanlarımız', 'text', 'homepage', 'Homepage fields section title (Turkish)'),
  ('homepage_fields_subtitle_en', 'explore our diverse portfolio of creative disciplines, each crafted with precision and passion', 'text', 'homepage', 'Homepage fields section subtitle (English)'),
  ('homepage_fields_subtitle_tr', 'tutkuyla ve özenle hazırlanmış çeşitli yaratıcı disiplinlerimizi keşfedin', 'text', 'homepage', 'Homepage fields section subtitle (Turkish)')
ON CONFLICT (setting_key) DO NOTHING;
